### ISSUE TITLE
Idea - alternative implementation of JVM persistence for server mode

### ISSUE THREAD

**Issue by chexxor** [neowit/tooling-force.com#12]
Server mode for this tool is killer, to be sure. I was curious about how you implemented that, so I took a look and found it is a web server managed by Akka actors.

I came across [Drip](https://github.com/ninjudd/drip) the other day and wondered if this project could make use of it. So, instead of "tooling-force.com" creating a web server, we just have clients execute "tooling-force.com" through Drip.

For example, instead of

    java -jar tooling-force.com-0.1.jar --action=refresh ...

we have clients do

    drip -cp tooling-force.com-0.1.jar --action=refresh ...

Just an idea.

**Comment by neowit** [comment]
I have not seen Drip before, looks interesting.  Thank you for sharing.  
Main benefits of running `tooling-force.com.jar` in server mode are: 
1. no need to spin up a JVM instance on every call
2. no need to load .jar in RAM on every call
3. ability to cache (lazily) certain things used for code completion:
    - DB Object(s) structure
    - results of apex code parser
    - Apex Documentation (to show method description with code completion)
4. For MS Windows users (when used with `vim-force.com` plugin ) - avoid showing a CMD.exe window on every call.

Based on Drip's documentation - it should cover item 1, not sure about 2 and definitely can not cover 3.  
If you do not use code completion then Drip may be worth trying. In case of `vim-force.com` plugin it is quite easy, just  set [g:apex_java_cmd](https://github.com/neowit/vim-force.com/blob/master/doc/force.com.txt#L1060) variable in your `.vimrc` to `drip` instead of `java` as per Drip's documentation. There should be no need to add any extra flags if `drip` actually proxies requests to `java`.

PS: Technically `Server mode` does not include a web server. It is just a basic socket server and does not respond to HTTP requests.

**Comment by chexxor** [comment]
Cool - sounds like it's not worth using Drip here, then. It might be useful if the caching is files instead of in-process-memory, but that might not be an appropriate design for caching.

Thanks for the explaining that! I'm sure it'll be useful to others who are also curious about this stuff.
