### ISSUE TITLE
Running all tests without a project path.

### ISSUE THREAD

**Issue by thomasdziedzic** [neowit/tooling-force.com#20]
Hi,

I was wondering if there is a way to run all the tests in an org without specifying the project path.

I would like to run all tests in an org on a schedule to notify me whenever there are test failures due to config changes.

Here is what I have so far.
```
java -jar tooling-force.com-0.3.6.6.jar --action=runTestsTooling --projectPath=$HOME/work/salesforce --responseFilePath=/dev/null --config=./login/sandbox.properties
```

Thanks for your help.

**Comment by neowit** [comment]
Project path is currently required because session Id (obtained via initial login) is stored in `<project-path>/.vim-force.com/session.properties` so we do not have to login every time.

To run all tests you could use something like this
```
java -jar tooling-force.com-0.3.6.6.jar --action=runTestsTooling --config='./login/sandbox.properties' --projectPath='$HOME/work/salesforce' --async=true --testsToRun='*' --responseFilePath='./some/file' --pollWaitMillis=1000 --maxPollRequests=1000
```

`--pollWaitMillis` and `--maxPollRequests ` are optional, but if you do not provide a value and your tests take a long time to run then default values for these two parameters may not be sufficient for your Org and tooling-force.com.jar may exit before tests run is done.

**Comment by neowit** [comment]
Ah, and the other reason to require project path is because it tries to deploy changes before running tests. The rationale is that CI type scenarios are expected to pull latest version from version control locally and deploy/test stuff, as opposed to just run tests on a remote version.

If you do not have an "up-to-date" version of apex code locally then you may have to do a manual (one-off) preparation:
1. setup project as usual
- you may want to reduce your project.xml to something minimal, e.g. just 1 class
2. run project refresh
- this will create project structure which should make `tooling-force.com.jar` happy.

After this (provided you do not change local files) - scheduled `--action=runTestsTooling` will see that there is nothing to deploy and will go straight to running tests in the Org.

**Comment by thomasdziedzic** [comment]
> The rationale is that CI type scenarios are expected to pull latest version from version control locally and deploy/test stuff, as opposed to just run tests on a remote version.

Ah I think I have a different workflow in mind. In a CI scenario, I have the code I want to deploy, so I want to do a deploy and run tests (forced to run in production by salesforce).

The scenario in mind is that I want to have a regression test which is different from the CI workflow.
Due to changes in salesforce that happen outside of a codebase which might affect it, the tests could start failing.

Thanks for the workaround idea.
I will investigate some more around the tooling api.

**Comment by neowit** [comment]
Thank you for the explanation.

Yes, presently (without that workaround I described above) you can not run regression tests. 
But your scenario makes sense, so I have added this (running tests without local project present) on my todo list.
Let's keep this issue open for now.

**Comment by thomasdziedzic** [comment]
thanks for providing the jar, is there a place I can find the code so that I can do a quick review?

**Comment by neowit** [comment]
Yes, [here](https://github.com/neowit/tooling-force.com/commit/e5e19f10dd6156cfb331bdda9f578e4910958b6e).

**Comment by thomasdziedzic** [comment]
I tested out the jar and I found that it works for the async option, but it doesn't seem to work for the synchronous version.

The async test I ran against all tests resulted in 90 seconds to finish the testing.
When I tried the sync test, before cancelling I got to:
```
[INFO] RunTests - Run tests Synchronous ... # elapsed: 17825s
```

With this command `java -jar tooling-force.com-0.3.6.7-20.jar --action=runTestsTooling --config=$HOME/.apex/login/sandbox-tomtom.properties --projectPath=$HOME/work/salesforce --async=false --testsToRun='*' --responseFilePath=/dev/null --pollWaitMillis=1000 --maxPollRequests=1000`

and I quit. It looks like the sync option has some kind of infinite loop.

So it looks like async works, but sync doesn't. If you want I can open a ticket for the infinite sync issue since it seems to show up without this new addition also.

**Comment by neowit** [comment]
> It looks like the sync option has some kind of infinite loop.

Actually there are no cycles in tooling-force.com.jar code which deals with running tests in synchronous mode.
I think it is SFDC. It is either too slow or just can not cope properly with the number of tests you make it to run in synchronous mode.

**Comment by thomasdziedzic** [comment]
I did some exploring to understand how this works.

runTestsTooling is used for sync testing:
https://github.com/neowit/tooling-force.com/blob/master/src/main/scala/com/neowit/apex/Session.scala#L1067-L1078

this method uses withRetry:
https://github.com/neowit/tooling-force.com/blob/master/src/main/scala/com/neowit/apex/Session.scala#L707-L726

I believe withRetry does have code paths for `com.sforce.ws.SoapFaultException` and `com.sforce.ws.ConnectionException` that could potentially loop since the behavior is to reset and try the code again. I wasn't able to find any "max retries" code which would short circuit the behavior. Do you think this would be possible?

I see that there are logging statements there so now I'm trying to figure out how to enable those to see if I can help debug this further.

**Comment by thomasdziedzic** [comment]
closing since this ticket has been implemented, opened a new ticket to track the infinite sync test issue.
