### ISSUE TITLE
Deployment to production silently fails for triggers with 0% code coverage.

### ISSUE THREAD

**Issue by thomasdziedzic** [neowit/tooling-force.com#6]
Using version 0.3.1.4:

```
RESULT=FAILURE
#SECTION START: ERROR LIST
#SECTION END: ERROR LIST
MESSAGE: {"id" : 3, "text" : "Code coverage details", "type" : "WARN"}
...
MESSAGE DETAIL: {"messageId" : 3, "text" : "QuoteLineItem: lines total 1; lines not covered 1; covered 0%", "type" : "WARN"}
...
MESSAGE: {"id" : 4, "text" : "Code coverage warnings", "type" : "WARN"}
```

**Comment by neowit** [comment]
Hi Thomas,

Thank you for reporting this.

Can you elaborate, what do you mean "silently fails"?

Do you run your deployment from command line or using vim with vim-force.com plugin?

With [vim plugin](/neowit/vim-force.com) you should get something like this
![image](https://cloud.githubusercontent.com/assets/552057/6981572/b33bcb52-d9fb-11e4-956d-9bf314142435.png)

if running from command line then you should check first line of the response file for `RESULT=SUCCESS`. If it is not there (like in your example) then it is safe to assume that last operation failed.

**Comment by thomasdziedzic** [comment]
I run it from the command line, more specifically, I built a tool around this that does our comlany deploys with a single command.

Even though the result says failure, there are no errors in the error list. I had to hunt down the culprit in the log file.

**Comment by neowit** [comment]
I see, thank you for the clarification.

This is the way SFDC reports coverage related issues - these are not reported as errors but as code coverage results. They do not correspond to specific places in a file (like syntax error or assert failure).

> I had to hunt down the culprit in the log file.  

if by "log file" you mean "response_xxx" file (or whatever you specified by `--responseFilePath` parameter) then it is not a log file as such. It is the file which clients of tooling-force.com.jar are supposed to parse to understand the result. Response file was designed specifically for this purpose.

If you have ideas how current report/response can be improved - let me know. Otherwise we can probably close this issue.

**Comment by thomasdziedzic** [comment]
Thanks for the clarification! This helped me understand the issue and I think as a result it helped me realize that you're trying the best you could given what salesforce is returning. I'll close this issue.
